import type { Post } from "@/types";

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    slug: "react-18-concurrent-features",
    title: "React 18 Concurrent Features 완벽 가이드",
    excerpt:
      "Suspense, useTransition, useDeferredValue를 실제 프로젝트에서 어떻게 활용하는지 예제와 함께 알아봅니다.",
    content: "# React 18 Concurrent Features\n\n...",
    thumbnail_color: "#1DC4D0",
    thumbnail_accent: "#0D9AA8",
    tag: "React",
    published_at: "2025-07-10T00:00:00Z",
    likes: 142,
    comments_count: 18,
    read_time: 8,
    published: true,
    created_at: "2025-07-10T00:00:00Z",
  },
  {
    id: "2",
    slug: "typescript-generic-patterns",
    title: "TypeScript 제네릭 패턴 — 실무에서 바로 쓰는 5가지",
    excerpt:
      "복잡한 타입 추론부터 조건부 타입까지, 실무에서 자주 마주치는 제네릭 패턴을 정리했습니다.",
    content: "# TypeScript Generic Patterns\n\n...",
    thumbnail_color: "#BF95FA",
    thumbnail_accent: "#9A6CF0",
    tag: "TypeScript",
    published_at: "2025-07-03T00:00:00Z",
    likes: 98,
    comments_count: 12,
    read_time: 6,
    published: true,
    created_at: "2025-07-03T00:00:00Z",
  },
  {
    id: "3",
    slug: "nextjs-15-app-router-blog",
    title: "Next.js 15 App Router로 블로그 만들기",
    excerpt:
      "Server Components와 Streaming을 활용해 성능 좋은 기술 블로그를 처음부터 구축하는 과정을 공유합니다.",
    content: "# Next.js 15 App Router\n\n...",
    thumbnail_color: "#FEC847",
    thumbnail_accent: "#E5A800",
    tag: "Next.js",
    published_at: "2025-06-28T00:00:00Z",
    likes: 215,
    comments_count: 31,
    read_time: 12,
    published: true,
    created_at: "2025-06-28T00:00:00Z",
  },
  {
    id: "4",
    slug: "tailwind-v4-migration",
    title: "Tailwind CSS v4 마이그레이션 완벽 가이드",
    excerpt:
      "v3에서 v4로 올리면서 달라진 것들과 주의해야 할 Breaking Changes를 코드로 정리했습니다.",
    content: "# Tailwind v4\n\n...",
    thumbnail_color: "#28CC8F",
    thumbnail_accent: "#1AAA74",
    tag: "CSS",
    published_at: "2025-06-15T00:00:00Z",
    likes: 76,
    comments_count: 9,
    read_time: 7,
    published: true,
    created_at: "2025-06-15T00:00:00Z",
  },
  {
    id: "5",
    slug: "core-web-vitals-optimization",
    title: "Core Web Vitals 90점 만들기 — 실전 최적화",
    excerpt:
      "LCP, FID, CLS를 개선하기 위한 구체적인 기법들과 실제 프로젝트에 적용한 결과를 공유합니다.",
    content: "# Core Web Vitals\n\n...",
    thumbnail_color: "#FA6690",
    thumbnail_accent: "#E0345C",
    tag: "성능최적화",
    published_at: "2025-06-01T00:00:00Z",
    likes: 183,
    comments_count: 24,
    read_time: 10,
    published: true,
    created_at: "2025-06-01T00:00:00Z",
  },
  {
    id: "6",
    slug: "first-open-source-contribution",
    title: "오픈소스 기여 처음 해봤습니다 — 후기",
    excerpt:
      "처음으로 오픈소스 PR을 머지시킨 경험과, 기여하기 좋은 프로젝트를 찾는 방법을 공유합니다.",
    content: "# 오픈소스 기여\n\n...",
    thumbnail_color: "#3879FA",
    thumbnail_accent: "#1B5CE0",
    tag: "개발일지",
    published_at: "2025-05-20T00:00:00Z",
    likes: 64,
    comments_count: 7,
    read_time: 5,
    published: true,
    created_at: "2025-05-20T00:00:00Z",
  },
];
